oicr-gsi/nabu

.env-example, README.md, app.js, components/fileqcs/fileQcsController.js, components/fileqcs/project_mappings.json, package.json, swagger.json
* ensures any search for "ExomeSequencingProject" also returns files for "EXSP"
And other updates, mostly to account for production things (like the IT security tests that shouldn't be logged)
=> Many names for projects

.snyk, app.js, package-lock.json, package.json, swagger.json, test/.eslintrc.yml
I'm not sure why the snyk file has duplicated lines, but it's not failing now.
=> Minor fixes

app.js, components/fileqcs/fileQcsController.js, test/fileqcTest.js, test/migrations/create_test_fpr.sql
=> Add route to list available projects and workflows

.snyk, app.js, components/fileqcs/fileQcsController.js, sql/V4__make_qcpassed_nullable.sql, swagger.json, test/fileqcTest.js, utils/logger.js
GR-621
* this allows users to save comments for why a file is not yet "PASS"-ing
=> allow users to save PENDING QCs

components/fileqcs/fileQcsController.js, test/fileqcTest.js, test/fpr-test.tsv, test/migrations/V9000__test_data.sql
=> Fix fileQCs merge

components/fileqcs/fileQcsController.js, swagger.json, test/fileqcTest.js
Adds an optional query parameter to show all FileQCs instead. 
GR-636 & #23
=> GETs default to returning single most recent FileQC

.snyk, app.js, components/fileqcs/fileQcsController.js, package-lock.json, package.json, swagger.json, test/fileqcTest.js
=> Stream FileQCs, and Swagger updates

components/fileqcs/fileQcsController.js, package-lock.json, package.json, sql/V5__timezoned_qcdate.sql
And nicer datetime formatting for users 
GR-644
=> Add timezone to qcDate in db

app.js, components/fileqcs/fileQcsController.js, swagger.json, test/fileqcTest.js
=> API update: POST to /delete-fileqcs

.env-example, CHANGELOG.md, components/fileqcs/fileQcsController.js, components/fpr/create_fpr_table.sql, components/fpr/rsync_full_fpr.sh, swagger.json, utils/logger.js
=> Get BamQC FileQCs for a given run

.env-example, app.js, components/fileqcs/fileQcsController.js, package-lock.json, package.json
=> Authenticate against AD for run report endpoint

.env-example, utils/logger.js
=> Don't die if request came from behind a proxy

.env-example, utils/logger.js, utils/prometheus.js
=> Fix check for remote address

.env-example, app.js
Hiding because this isn't in use and won't work as intended (see GR-1284 for description of fix required).
=> Hide AD endpoint behind a flag

.env-example, node_modules/.bin/semver, package-lock.json
Getting these in, then making new PR for version 3.0.0
=> more fixes

.github/dependabot.yml, .github/pull_request_template.md, CHANGELOG.md
=> Add dependabot and PR template

CHANGELOG.md, app.js, components/fileqcs/fileQcDao.js, components/fileqcs/fileQcsController.js, swagger.json
=> Re-add /fileqcs-only endpoint, and fix the metric for getting the FPR latest update time

.github/workflows/npm.yml
=> Automate testing

CHANGELOG.md, swagger.json
=> Update OpenAPI documentation to include FileQC's `alert` property for /get-fileqcs endpoint

.nvmrc, CHANGELOG.md, README.md, node_modules/.bin/mkdirp, node_modules/.bin/which, package-lock.json, sql/V008__add_case_and_archive.sql
Jira ticket: GP-3983 and GP-3984
- [~] Updates developer documentation
=> Add case archiving tables

CHANGELOG.md, app.js, components/case/caseController.js, components/case/caseDao.js, package.json, swagger.json, test/archiveTest.js, utils/urlSlugs.js
Jira ticket: GP-3990, GP-3991, GP-3992
=> Add endpoints for updating case archives

CHANGELOG.md, app.js, components/case/caseController.js, components/case/caseDao.js, swagger.json, test/archiveTest.js
Jira ticket: GP-3994
This will be used by Shesmu
=> Add streaming endpoint to get all case data

CHANGELOG.md, components/case/caseController.js
N/A Updates developer documentation
=> Add validation that unload file is passed to certain case archive methods

README.md
Jira ticket:
- [x ] Updates developer documentation
=> some README changes based on setup experience

CHANGELOG.md, app.js, components/case/caseController.js, components/case/caseDao.js, swagger.json, test/archiveTest.js
=> Query for outstanding case archiving work

CHANGELOG.md, components/case/caseController.js, swagger.json
=> Fix API docs and add ability to request Vidarr metadata for a case

app.js, components/signoffs/signoffController.js, components/signoffs/signoffDao.js, swagger.json, test/signoffTest.js
=> Glt3961 addmultisignoffs

CHANGELOG.md, test/authTest.js, utils/apiAuth.js
Jira ticket: https://jira.oicr.on.ca/browse/GP-4162
=> Gp 4162.api hanging no key

swagger.json
(openapi 3+ requirement)
Jira ticket:
=> add in schema to swagger.json to prevent infinite loading wheel 

CHANGELOG.md, components/signoffs/signoffController.js, sql/V009__create_signoff_table.sql, sql/V011__add_deliverable.sql, swagger.json, test/migrations/V9000__test_data.sql, test/signoffTest.js
Jira ticket: https://jira.oicr.on.ca/browse/GP-4170
=> Gp 4170.add deliverables release

CHANGELOG.md, components/signoffs/signoffController.js, components/signoffs/signoffDao.js, sql/V012__fix_signoff_unique_index.sql, swagger.json
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4095
=> [GLT-4095] fixed saving sign-off deliverable

CHANGELOG.md, components/case/caseController.js, swagger.json, test/archiveTest.js
Jira ticket: Part of https://jira.oicr.on.ca/browse/GP-4121 and https://jira.oicr.on.ca/browse/GP-4072
=> add API key requirement to create case archive

CHANGELOG.md, README.md, node_modules/.bin/flyway, package-lock.json, package.json
=> Dependency updates

.github/workflows/npm.yml, CHANGELOG.md, README.md, test/setup_test_dbs.sh
=> Update to current + next NodeJS version, and current PostgreSQL version

.github/pull_request_template.md
=> Improve PR template so all boxes can be checked off at PR creation time

CHANGELOG.md, components/case/caseController.js, components/case/caseDao.js, test/archiveTest.js, utils/controllerUtils.js
Jira ticket: https://jira.oicr.on.ca/browse/GP-4882
=> set stopProcessing when any archive breaking change submitted
